<?php

function oc_krimi_siden_menu() {
  $items['krimi/get-authors-in-genre/%'] = array(
    'page callback' => 'oc_krimi_siden_get_similar_authors_by_genre',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
   $items['krimi/get-author-genres/%'] = array(
    'page callback' => 'oc_krimi_siden_get_author_genres',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
      $items['krimi/get-books-by-genre/%'] = array(

    'page callback' => 'oc_krimi_siden_get_books_by_genre',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['krimi/get-books-by-author/%'] = array(

    'page callback' => 'oc_krimi_siden_get_books_by_author',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['krimi/get-books-by-main-char/%'] = array(
    'page callback' => 'oc_krimi_siden_get_books_by_main_char',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}
/**
 * Implements hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * args, contexts, content_types.
 */
function oc_krimi_siden_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}
 /*
  * Register a custom theme template
  */
 function oc_krimi_siden_theme($existing, $type, $theme, $path)
{

    return array(
      'krimi_linked_block' => array(
        'variables' => array(),
        'template' => 'krimi_linked_block',
        'path' => drupal_get_path('module', 'oc_krimi_siden') . '/templates'
      ),
    );
}
function oc_krimi_siden_get_single_rdf_internal($faust)
{
    $query = 'PREFIX schema: <http://schema.org/> CONSTRUCT WHERE { ?genre schema:productID "faust:%#%" .?genre ?o ?p}';
    $query = str_replace('%#%', $faust, $query);
    $url = "http://lod.fynbib.dk:3030/krimisiden/sparql?query=".rawurlencode($query) . "&output=json";
    $data = file_get_contents($url);
    return json_decode($data);
}
/*
 * Api methods
 */

function oc_krimi_siden_get_books_by_location($location)
{
    $location = "http://krimisiden.dk/content.php?" . $location;
    $query = 'PREFIX schema: <http://schema.org/> CONSTRUCT WHERE { ?genre schema:contentLocation <%#%> .?genre ?o ?p}';
    $query = str_replace('%#%', $location, $get_books_by_genre_sparql);
    $url = "http://lod.fynbib.dk:3030/krimisiden/sparql?query=".rawurlencode($query) . "&output=json";
    $data = file_get_contents($url);
    echo $data;
    drupal_exit();
}
function oc_krimi_siden_get_books_by_main_char($main_char)
{
    $main_char = "http://krimisiden.dk/content.php?" . $main_char;
    $get_books_by_main_char_sparql = 'PREFIX schema: <http://schema.org/> CONSTRUCT WHERE { ?mainchar schema:mainCharacter "%#%" . ?mainchar ?o ?p }';
    $get_books_by_main_char_sparql = str_replace('%#%', $main_char, $get_books_by_main_char_sparql);
    $url = "http://lod.fynbib.dk:3030/krimisiden/sparql?query=".rawurlencode($get_books_by_main_char_sparql) . "&output=json";
    $data = file_get_contents($url);
    echo $data;
    drupal_exit();
}
function oc_krimi_siden_get_books_by_genre($genre)
{
    $genre = "http://krimisiden.dk/content.php?" . $genre;
    $get_books_by_genre_sparql = 'PREFIX schema: <http://schema.org/> CONSTRUCT WHERE { ?genre schema:genre <%#%> .?genre ?o ?p}';
    $get_books_by_genre_sparql = str_replace('%#%', $genre, $get_books_by_genre_sparql);
    $url = "http://lod.fynbib.dk:3030/krimisiden/sparql?query=".rawurlencode($get_books_by_genre_sparql) . "&output=json";
    $data = file_get_contents($url);
    echo $data;
    drupal_exit();
}
function oc_krimi_siden_get_books_by_author($author)
{
    $get_books_by_author_sparql = 'PREFIX schema: <http://schema.org/> CONSTRUCT WHERE { ?author schema:author "%#%" . ?author ?o ?p }';
    $get_books_by_author_sparql = str_replace('%#%', $author, $get_books_by_author_sparql);
    $url = "http://lod.fynbib.dk:3030/krimisiden/sparql?query=".rawurlencode($get_books_by_author_sparql) . "&output=json";
    $data = file_get_contents($url);
    echo $data;
    drupal_exit();
}
function oc_krimi_siden_get_author_genres($author)
{
    $get_book_genres_sparql = 'PREFIX schema: <http://schema.org/> SELECT distinct ?identifier ?label ?genre_billede WHERE {  ?s schema:author "%#%" .  ?s schema:genre ?identifier .  ?identifier schema:name ?label .  BIND(CONCAT("", ?label, ".jpg") AS ?genre_billede) .}';
    $get_book_genres_sparql = str_replace('%#%', $author, $get_book_genres_sparql);
    $url = "http://lod.fynbib.dk:3030/krimisiden/sparql?query=".rawurlencode($get_book_genres_sparql) . "&output=json";
    $data = file_get_contents($url);
    echo $data;
    drupal_exit();
    
}
function oc_krimi_siden_get_similar_authors_by_genre($faust)
{
    $get_authors_in_book_genre_sparql = 'PREFIX schema: <http://schema.org/> select distinct ?author {  ?s schema:productID "faust:%#%" .  ?s schema:genre ?genre .  ?books schema:author ?author .  filter(isLiteral(?author)) }group by ?author order by rand() LIMIT 50';
    $get_authors_in_book_genre_sparql = str_replace('%#%', $faust, $get_authors_in_book_genre_sparql);
    $url = "http://lod.fynbib.dk:3030/krimisiden/sparql?query=".rawurlencode($get_authors_in_book_genre_sparql) . "&output=json";
    $data = file_get_contents($url);
    echo $data;
    drupal_exit();
}